import { Word } from "../models/Word";

export const gameWords1: Word[] = [
    { word: "SHINDIG", category: "SHINDIG" },
    { word: "BOMBORAASCLAAT", category: "SHINDIG" },
    { word: "POLO G STOPLIGHT", category: "SHINDIG" },
    { word: "NLE FREAK", category: "SHINDIG" },
    { word: "TIM HORTONS", category: "FIRST DATES" },
    { word: "NAMING PROVINCES AT DAIRY QUEEN", category: "FIRST DATES" },
    { word: "RMS PLAYGROUND", category: "FIRST DATES" },
    { word: "CHRISTMAS WITH THE KRANKS", category: "FIRST DATES" },
    { word: "THAT'S NOT THE MIYAGI DO WAY", category: "COBRA KAI" },
    { word: "IF I DON'T PASS TRIG THIS SEMESTER...", category: "COBRA KAI" },
    { word: "LET THE GAMES BEGIN 👹", category: "COBRA KAI" },
    { word: "SIDE DAB YUH", category: "COBRA KAI" },
    { word: "WASP INVASION", category: "SEEMORE" },
    { word: "POOL", category: "SEEMORE" },
    { word: "FIRE ALARM", category: "SEEMORE" },
    { word: "APARTMENT", category: "SEEMORE" },
  ];

  export const gameWords2: Word[] = [
    { word: "QUIET ROOM", category: "STUDYING" },
    { word: "THE ROCK ENERGY DRINK", category: "STUDYING" },
    { word: "WEIRD GUY DANCING ON THE WINDOW", category: "STUDYING" },
    { word: "PHONE DEAD", category: "STUDYING" },
    { word: "STEAL SHOES", category: "FRANKIE" },
    { word: "POOP IN SARAHS ROOM", category: "FRANKIE" },
    { word: "EAT WORMS", category: "FRANKIE" },
    { word: "A GOOD BOY (SOMETIMES)", category: "FRANKIE" },
    { word: "WORLDLE", category: "GAMES WE PLAY" },
    { word: "GUESS THE COUNTRY", category: "GAMES WE PLAY" },
    { word: "GLOBLE", category: "GAMES WE PLAY" },
    { word: "GUESS THE PERSON", category: "GAMES WE PLAY" },
    { word: "COUNTRY MUSIC", category: "POOR TASTE" },
    { word: "TWILIGHT", category: "POOR TASTE" },
    { word: "ASMR", category: "POOR TASTE" },
    { word: "BRENT RIVERA", category: "POOR TASTE" },
  ];

  export const gameWords3: Word[] = [
    { word: "CHOCOLATE MILK", category: "DRINKS THAT WE LIKE" },
    { word: "BOBA", category: "DRINKS THAT WE LIKE" },
    { word: "BUBBLY", category: "DRINKS THAT WE LIKE" },
    { word: "ICE COFFEE WITH PUMPKIN SPICE", category: "DRINKS THAT WE LIKE" },
    { word: "BLUEBERRY HILL", category: "CAPE BRETON" },
    { word: "LICK A CHICK", category: "CAPE BRETON" },
    { word: "AK-47", category: "CAPE BRETON" },
    { word: "HORSE ATTACK", category: "CAPE BRETON" },
    { word: "SCARY MOVIES", category: "THINGS IM SCARED OF" },
    { word: "BIRDS", category: "THINGS IM SCARED OF" },
    {
      word: "WALKING IN FRONT OF YOU UP STAIRS",
      category: "THINGS IM SCARED OF",
    },
    { word: "WHEN YOU TRY TO POP MY PIMPLE", category: "THINGS IM SCARED OF" },
    { word: "GARAGE", category: "PLACES YOU WORKED AT" },
    { word: "CT", category: "PLACES YOU WORKED AT" },
    { word: "TOWN OF RIVERVIEW", category: "PLACES YOU WORKED AT" },
    { word: "CHURCH IN DIEPPE (I THINK)", category: "PLACES YOU WORKED AT" },
  ];